[build]
  publish = "web-build"
  command = "npm run build-react"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"